- name: configure DB server
  hosts: db
  become: yes
  vars:
    mysql_root_password: ExpenseApp@1
  tasks:
  - name: Install MySQL Server
    ansible.builtin.command: dnf install mysql-server -y

  - name: Start and Enable MySQL server
    ansible.builtin.service:
      name: mysqld
      state: started
      enabled: yes

  - name: setup root password
    ansible.builtin.command: "mysql_secure_installation --set-root-pass {{ mysql_root_password }}"